### ISSUE TITLE
component is provisional

### ISSUE THREAD

**Issue by daviem** [Maikuolan/phpMussel#200]
Please use this template when reporting bugs, problems, issues, etc.

### phpMussel version used (if known, please also include the exact commit hash).
eg 1.0.0-DEV@c8778924df2cb94d40796a0876005c46b711e76e

### PHP SAPI used (`<?php echo php_sapi_name(); ?>`).
eg cgi-fcgi

### PHP version installed (`<?php echo phpversion(); ?>`).
eg 7.1.0

### Operating system used (`<?php echo php_uname(); ?>`).
eg Linux localhost 2.4.21-0.13mdk #1 Fri Mar 14 15:08:06 EST 2003 i686

---
## Issue
Please describe the problem here.

### Expected behavior
What should normally happen?

### Actual behavior
What is actually happening?

### Steps to reproduce the behavior
* step 1
* step 2
* step 3
* …

### Last known working version without this issue.
---

**Comment by Maikuolan** [comment]
Hi @daviem.

What is the issue, exactly? It seems you haven't changed anything from the repository issue template and haven't described the issue in more detail, so I'm not quite sure the purpose of this issue.

Thanks.

**Comment by Maikuolan** [comment]
*Marking as invalid and closing.*
