### ISSUE TITLE
Getting error "Function name must be a string" after initial setup.

### ISSUE THREAD

**Issue by sudhanshu-a3** [Maikuolan/phpMussel#206]
Server Information:-
phpMussel version used: 1.11.0
Branch latest stable: 1.11.0 – Latest stable: 1.11.0 – Latest unstable: 2.0.0
PHP version used: 7.0.33-10+ubuntu18.04.1+deb.sury.org+1

SAPI used: apache2handler
Operating system used: Linux A3-576 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64

Extensions:-

Extension | Installed/Available
-- | --
PCRE | Yes (7.0.33-10+ubuntu18.04.1+deb.sury.org+1)
cURL | Yes (7.0.33-10+ubuntu18.04.1+deb.sury.org+1)
APCu | No
Memcached | No
Redis | No
PDO | Yes (7.0.33-10+ubuntu18.04.1+deb.sury.org+1)
Bz2 | No
Lzf | No
Rar | No
Zip | Yes (1.13.5)

---
## Issue
I am getting error 
` "Function name must be a string".`
Am following the basic documentation guide provided.
Added folder phpMussel in my server root directory and included in the file 
`include_once __DIR__ . '/../vendor/phpMussel/loader.php';`
then i called
`$results = $phpMussel['Scan'](__DIR__.'/../phpMussel/_testfiles', true, true);`

then i get the following error.
`"Function name must be a string"`.
I tried to var_dump ($phpMussel) and it return NULL.
When i tried var_dump on loader.php then it return a big array with various key values.
I tried `require_once` also instead of `include once` but nothing happen.

**Comment by Maikuolan** [comment]
Hi,

Sorry to hear about this problem, and thanks for reporting.

Can I confirm with you whether the "[cleanup](https://github.com/phpMussel/Docs/blob/master/readme.en.md#cleanup)" configuration directive has been set as `true` or `false`?

Thanks. :-)

**Comment by sudhanshu-a3** [comment]
Hello,
Thanks for your indication. Its true and that's why its not working. I set it to False and now its working.

Cheers.
