### ISSUE TITLE
Cronable update PhpMussel gives Failed to update! « +0 bytes | -0 bytes 

### ISSUE THREAD

**Issue by sudhanshu-a3** [Maikuolan/phpMussel#207]
Server Information:-
phpMussel version used: 1.11.0
Branch latest stable: 1.11.0 – Latest stable: 1.11.0 – Latest unstable: 2.0.0
PHP version used: 7.0.33-10+ubuntu18.04.1+deb.sury.org+1

SAPI used: apache2handler
Operating system used: Linux A3-576 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64

Extensions:-

Extension | Installed/Available
-- | --
PCRE | Yes (7.0.33-10+ubuntu18.04.1+deb.sury.org+1)
cURL | Yes (7.0.33-10+ubuntu18.04.1+deb.sury.org+1)
APCu | No
Memcached | No
Redis | No
PDO | Yes (7.0.33-10+ubuntu18.04.1+deb.sury.org+1)
Bz2 | No
Lzf | No
Rar | No
Zip | Yes (1.13.5)

Issue
I am getting error
`[phpMussel] – Failed to update! « +0 bytes | -0 bytes | 0.009 »`
Whenever i tried to update using "Cronable class"

My update code is as per standard example given in "Cronable" i.e.

        `require_once CRONABLE_CLASS;
        $Cronable = new \Maikuolan\Cronable\Cronable();
        $Cronable->localUpdate('phpMussel', CRONABLE_USERNAME, CRONABLE_PASSWORD,PHP_MUSSEL_CLASS);
        echo $Cronable->Output;`

It always gives me this error:- 
`Cronable v1.2.0
Time: Tue, 17 Sep 2019 06:21:10 +0000
[phpMussel] – Failed to update! « +0 bytes | -0 bytes | 0.009 »`

Am following the basic documentation guide provided.

**Comment by Maikuolan** [comment]
Hi @sudhanshu-a3,

Sorry for the delayed reply; Had been caught up with other things the past two days.

Just to confirm: Have you created an account at the phpMussel front-end for Cronable to use?

**Comment by sudhanshu-a3** [comment]
Yes i did it.

**Comment by Maikuolan** [comment]
Been doing some testing at my end, trying to see which different ways I could replicate the problem. If you try to update via the front-end updates page (i.e., not using Cronable), does it update successfully? Or does the same error appear there too?

**Comment by DanielRuf** [comment]
Probably the file owner or permissions are the problem.

**Comment by Maikuolan** [comment]
@sudhanshu-a3, if you could confirm when you've got a spare moment, we can try to move forward with this issue, or close it if the problem has already been resolved.

1; Checking whether the problem persists when manually updating via the front-end:

> If you try to update via the front-end updates page (i.e., not using Cronable), does it update successfully? Or does the same error appear there too?

..and 2; Checking file permissions:

> Probably the file owner or permissions are the problem.

Cheers. :-)

**Comment by Maikuolan** [comment]
No further replies from OP since almost a month now. I'll assume the problem has been resolved. Marking and closing accordingly.
