### ISSUE TITLE
Inaccurate Progress

### ISSUE THREAD

**Issue by mrme44** [Maikuolan/phpMussel#225]
### phpMussel version used (if known, please also include the exact commit hash).
Using the latest of everything, as of today.

### Signatures version (if known).
The latest.

### PHP SAPI used (`<?php echo php_sapi_name(); ?>`).
cli

### PHP version installed (`<?php echo phpversion(); ?>`).
7.4.10

### Operating system used (`<?php echo php_uname(); ?>`).
>uname -a
Linux 88877.cloudwaysapps.com 4.9.0-13-amd64 #1 SMP Debian 4.9.228-1 (2020-07-05) x86_64 GNU/Linux

---
## Issue
When using the example cli.php the progress is not reporting accurate numbers

### Expected behavior
The x/x progress should accurately reflect the number of files scanned

### Actual behavior
The progress starts out good, but then the total number of files starts increasing to a number bigger than the actual number of files in the directory being scanned.

### Steps to reproduce the behavior
1) I can reproduce this by setting up a simple phpMussel setup in the home directory with the following
```
    mkdir antivirus
    cd antivirus
    composer require phpmussel/core phpmussel/cli phpmussel/phpmailer

    # Download signatures
    mkdir phpmussel-signatures
    cd phpmussel-signatures/
    wget https://raw.githubusercontent.com/phpMussel/SigTool/master/SigTool.php
    wget https://raw.githubusercontent.com/phpMussel/SigTool/master/YAML.php
    php SigTool.php xpmd
    cd ..

    touch phpmussel.ini

    cat << EOF > cli.php
    <?php
    // Path to vendor directory.
    \$Vendor = __DIR__ . DIRECTORY_SEPARATOR . 'vendor';

    // Composer's autoloader.
    require \$Vendor . DIRECTORY_SEPARATOR . 'autoload.php';

    \$Loader = new \phpMussel\Core\Loader();
    \$Scanner = new \phpMussel\Core\Scanner(\$Loader);
    \$CLI = new \phpMussel\CLI\CLI(\$Loader, \$Scanner);

    unset(\$CLI, \$Scanner, \$Loader);
EOF
```

2) And then the problem happens when scanning any folder. For example I had a copy of this WordPress theme https://wordpress.org/themes/twentynineteen/ that I tried scanning. After running
`php cli.php`
I ran
`scan /home/master/twentynineteen`
And the progress started at 0/123 files and ended at 284/284.

However there are only 92 files
> find /home/master/twentynineteen/ -type f | wc -l
92

**Comment by Maikuolan** [comment]
Thanks for reporting this. :-)

I've found the problem and I'm trying out a possible fix now. I'll reply again shortly after committing some changes.

**Comment by Maikuolan** [comment]
Fixed (https://github.com/phpMussel/Core/commit/ab4f6b48ca9e39c86aa02f52689b075d871f8904). :-)
