### ISSUE TITLE
Feature Request - Custom Templates/Custom Assets Path

### ISSUE THREAD

**Issue by shadowstriker15** [Maikuolan/phpMussel#227]
Hello, I was wondering if it is currently possible to use a custom template? I could not find a way where I could pass a different Assets path to look for a custom template outside of the vendor's directory. Thank you

**Comment by Maikuolan** [comment]
Not *yet* possible, but I like the idea. I'll experiment with this shortly to try to come up with something workable. Thanks for the suggestion. :-)

**Comment by Maikuolan** [comment]
I've pushed some small changes which should allow for this now, I think.

(https://github.com/phpMussel/FrontEnd/commit/8131da7b2e2b95078425b5a7e81ba822af6187aa + https://github.com/phpMussel/Web/commit/14b140e3efc4b337f92501ee1a4f1aa35e568901).

I haven't yet documented these changes anywhere, but it should now be possible to define a custom assets path after instantiating the objects (FrontEnd or Web), as long as done prior to calling `scan()` (Web) or `view()` (FrontEnd).

```PHP
$Loader = new \phpMussel\Core\Loader();
$Scanner = new \phpMussel\Core\Scanner($Loader);
$FrontEnd = new \phpMussel\FrontEnd\FrontEnd($Loader, $Scanner); 
$FrontEnd->CustomAssetsPath = '/path/to/assets/foo/bar/etc';
$FrontEnd->view();
```

```PHP
$Loader = new \phpMussel\Core\Loader();
$Scanner = new \phpMussel\Core\Scanner($Loader);
$Web = new \phpMussel\Web\Web($Loader, $Scanner);
$Web->CustomAssetsPath = '/path/to/assets/foo/bar/etc';
$Web->scan();
```

Let me know how it goes, and if you had any other ideas, suggestions and so on. :-)

**Comment by shadowstriker15** [comment]
That's great, can't wait to check it out!
