### ISSUE TITLE
Laravel + Docker - Unable to build the path

### ISSUE THREAD

**Issue by igorcfreittas** [Maikuolan/phpMussel#237]
Hello, I'm facing a problem using the library with laravel inside a docker container, I would like you to help me please

When using it inside the container, it is not able to find the library path, however, using it outside the container (with the command: **php artisan serve)** it works correctly, I will put some information that may be useful

Laraval debug output: https://flareapp.io/share/DPybrlD7

**_Code breaks in instance of Loader and Scanner_**

**Note: The container works correctly, it goes up and shows the frontend, it just doesn't work when you need to import the libraries, I did a test by installing and importing the Laravel debugbar and it worked, it seems that it is something specific to PHPMussel**

### Controller:

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use phpMussel\Core\Loader;
use phpMussel\Core\Scanner;

use Illuminate\Support\Facades\Storage;

class ScanController extends Controller
{
    private $loader;
    private $scanner;
    private $fileDebugOutput;

    private $config = [
        'configuration' => 'phpmussel.yml',
        'cache' => '/phpmussel-cache',
        'quarantine' => '/phpmussel-quarantine',
        'signatures' => '/phpmussel-signatures',
    ];

    public function __construct(Loader $loader, Scanner $scanner)
    {
        $root = base_path();
        $loader = new Loader(
            $root . $this->config['configuration'],
            $root . $this->config['cache'],
            $root . $this->config['quarantine'],
            $root . $this->config['signatures']
        );
        $scanner = new Scanner($loader);
        $scanner->setScanDebugArray($this->fileDebugOutput);

        $this->loader = $loader;
        $this->scanner = $scanner;
    }

    public function redirectTo() //just to redirect if call with GET on browser tab
    {
        return view('form_scan');
    }

    public function scan(Request $request, $isView = 0)
    {
        $file = $request->file('file');
        if (!$file) {
            return response(['message' => 'Informe ao menos um arquivo para upload.'], 401);
        }

        $fileName = Storage::put('', $file);
        $filePath = Storage::path($fileName);

        $scanResult = $this->scanner->scan($filePath);

        $response = json_encode([
            'origin' => $this->loader->Configuration['core']['ipaddr'],
            'objects_scanned' => $this->loader->InstanceCache['ObjectsScanned'] ?? 0,
            'detections_count' => $this->loader->InstanceCache['DetectionsCount'] ?? 0,
            'scan_errors' => $this->loader->InstanceCache['ScanErrors'] ?? 1,
            'hash_references' => $this->loader->HashReference,
            'why_flagged' => implode($this->loader->L10N->getString('grammar_spacer'), $this->loader->ScanResultsText),
            'extended_original_result' => $scanResult,
            'file_debug_output' => $this->fileDebugOutput,
        ]);

        Storage::delete($fileName);

        $redirectToViewWithResponse = $isView;
        if ($redirectToViewWithResponse) {
            return view('form_scan', ['response' => $response]);
        }

        return response($response, 200);
    }
}
```

### Project structure:

![image](https://github.com/phpMussel/phpMussel/assets/22238386/47ac424d-e1f4-49da-9e2f-175047b2ef51)

###  PHP Dockerfile:
 
```Dockerfile
FROM php:8.1-fpm

ARG user=dev
ARG uid=1000

RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN useradd -G www-data,root -d /home/$user $user
RUN mkdir -p /home/$user/.composer && chown -R $user:$user /home/$user

WORKDIR /var/www
```

### NGINX default.conf file

```nginx
server {
    listen 80;
    server_name netlex_scan_api;
    index index.php index.html index.htm;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/public;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass netlex_scan_api:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
```

### NGINX Dockerfile

```Dockerifle
FROM nginx:1.17-alpine

COPY ./default.conf /etc/nginx/conf.d
```

### docker-compose.yml

```Dockerfile
version: "3.7"

services:
  netlex_scan_api:
    build: ./docker/php
    container_name: netlex_scan_api
    restart: unless-stopped
    volumes:
      - ./scan:/var/www
    ports:
      - "9000:80"
    networks:
      - netlex_scan

  netlex_nginx:
    build: ./docker/nginx
    container_name: netlex_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    links:
      - netlex_scan_api
    volumes:
      - ./scan:/var/www
    networks:
      - netlex_scan

networks:
  netlex_scan:
    driver: bridge

```

**Comment by Maikuolan** [comment]
Could be a permissions problem, maybe. Does the user running the Docker instance have write permissions for the Docker volume?

The *"Unable to build the path"* exception is generated by the `buildPath` method when it attempts to build paths (e.g., for phpMussel's cache, quarantine directories, etc) and some kind of failure occurs (e.g., calls to `is_dir`, `mkdir`, or `is_writable` return false).

Assuming the failure is due to `mkdir`, it might be possible to work around the immediate problem by manually creating those directories, so that `buildPath` will see that they already exist and thus not attempt to create them automatically. If the failure is due to `is_dir` or `is_writable` though, that likely won't achieve anything. There could also be other problems that appear down the track if there's a permissions problem happening which isn't addressed (e.g., attempting to write some files to the quarantine, or updating the configuration, or logging, or some other operation which requires writing data isn't able to do so due to insufficient permissions).

Otherwise, if it isn't a permissions problem, I might need to experiment a little at my end to get to the bottom of what's going on, because I haven't seen this particular situation occur before.

**Comment by igorcfreittas** [comment]
Thanks for the help, I looked more closely and it was basically a permission problem, I needed to point out the correct user to be used inside the container, I added this line in the PHP Dockerfile:

`USER dev`

and the problem is solved, thanks @Maikuolan

**Comment by Maikuolan** [comment]
Happy to help. :-)
