### ISSUE TITLE
PHP Warnings - preg_match()

### ISSUE THREAD

**Issue by williamsjor** [Maikuolan/phpMussel#238]
Hello,
I'm using PHP version 8.1.23 and the latest 3.4.1 PHP Mussel. I'm getting these Php warnings:
PHP Warning:  preg_match(): Compilation failed: regular expression is too large at offset 334 in /phpmussel/vault/functions.php on line 2627
PHP Warning:  preg_match(): Compilation failed: number too big in {} quantifier at offset 78 in /phpmussel/vault/functions.php on line 2627
PHP Warning:  preg_match(): Compilation failed: number too big in {} quantifier at offset 54 in /phpmussel/vault/functions.php on line 2627
PHP Warning:  preg_match(): Compilation failed: regular expression is too large at offset 93 in /phpmussel/vault/functions.php on line 2627
PHP Warning:  preg_match(): Compilation failed: regular expression is too large at offset 104 in /phpmussel/vault/functions.php on line 2627
PHP Warning:  preg_match(): Compilation failed: regular expression is too large at offset 112 in /phpmussel/vault/functions.php on line 2627
PHP Warning:  preg_match(): Compilation failed: regular expression is too large at offset 107 in /phpmussel/vault/functions.php on line 2627
PHP Warning:  Undefined array key "CacheModified" in /phpmussel/vault/functions.php on line 4628

Hope this helps and let me know if you need anything else. Thank you!

**Comment by Maikuolan** [comment]
Are you sure the correct version has been installed? There's a `functions.php` file in v2 and earlier versions, but there isn't any such file in v3 and onward. Seeing errors in any v3 installation refer to that particular file makes me wonder whether something has gone wrong during installation.

**Comment by williamsjor** [comment]
Hello Caleb,

Thanks for the quick response. Yea it looks like when I upgraded using
composer something went wrong and some of the old files were still around.
I wiped and reinstalled and I don't see that file so it should be good now.
Thank you very much.

Sincerely,
Joshua

**Comment by Maikuolan** [comment]
You're welcome, and happy to help. :-)
